### ISSUE TITLE
Turning off the TV should not lead to errors.

### ISSUE THREAD

**Issue by rshadow** [mrstegeman/chromecast-adapter#9] opened 2020-05-26 14:58 UTC
Now when the TV is turned off, I see errors in the log.
It seems that you just need to write that the TV was not found. For example, with the level of INFO.
```
2020-05-26 16:02:58.704 ERROR  : Failed to get property volume: getProperty: device: globe-675aabd2b12ef90f71df12efdb405ad3._googlecast._tcp.local. not found.
2020-05-26 16:02:58.705 ERROR  : Failed to get property on: getProperty: device: globe-675aabd2b12ef90f71df12efdb405ad3._googlecast._tcp.local. not found.
2020-05-26 16:02:58.705 ERROR  : Failed to get property playing: getProperty: device: globe-675aabd2b12ef90f71df12efdb405ad3._googlecast._tcp.local. not found.
2020-05-26 16:02:58.706 ERROR  : Failed to get property muted: getProperty: device: globe-675aabd2b12ef90f71df12efdb405ad3._googlecast._tcp.local. not found.
2020-05-26 16:02:58.706 ERROR  : Failed to get property app: getProperty: device: globe-675aabd2b12ef90f71df12efdb405ad3._googlecast._tcp.local. not found.
```

**Comment by mrstegeman** [comment] 2020-05-26 16:49
This is actually caused by the gateway, not the adapter, and it should only be seen when the gateway is (re)started while the Chromecast is powered off. It should then go away once the Chromecast is powered on. Is that correct?

**Comment by rshadow** [comment] 2020-05-26 19:06
I think yes.

**Comment by mrstegeman** [comment] 2020-05-26 19:07
Ok. I'm going to close this since there's really nothing to be done.

**Closed as completed by mrstegeman** 2020-05-26 19:07 UTC
